### get root coffees controller

GET http://localhost:3000/coffees
Accept: application/json

### get root coffees flavours

GET http://localhost:3000/coffees/flavors
Accept: application/json

### get coffees by id

GET http://localhost:3000/coffees/124
Accept: application/json

### create coffees with body

POST http://localhost:3000/coffees/
Content-Type: application/json

{
 "name": "Old cat",
  "brand": "everyone"
}


### update a coffe by id

PATCH http://localhost:3000/coffees/124


### delete a coffe by id

DELETE http://localhost:3000/coffees/124
